INSERT INTO users (first_name, last_name, email, password, date_of_birth, address, gender, about_me, starsign, vaccinated, distance)
VALUES 
('Jordan', 'Peterson', 'jpete@email.com', 'password', '1992-02-15', 'Toronto', 'Non-Binary', 'I love going out and making new friends!', 'Aquarius', 'Yes', 27),
('Yuti', 'Reswick', 'itsyuti@email.com', 'password', '1990-05-09', 'Brampton', 'Male', 'I live for the Raptors. Hit me up if you wanna shoot some hoops', 'Taurus', 'Yes', 22),
('Eva', 'Bell', 'evab@email.com', 'password', '1998-10-23', 'Toronto', 'Female', 'I love to hike and go on adventures!', 'Scorpio', 'Yes', 24),
('Adrian', 'Williams', 'awills@email.com', 'password', '1994-03-19', 'Toronto', 'Male', 'Photography is my passion. Always down for a collab', 'Pisces', 'No', 27),
('Alexa', 'Jones', 'alexajones@email.com', 'password', '1986-09-12', 'Scarborough', 'Undisclosed', 'Always looking for book recommendations! Let me know what you are reading', 'Virgo', 'Yes', 51),
('Kelly', 'Chu', 'kelly@email.com', 'password', '1998-09-11', 'Toronto', 'Female', 'I only love three things: My dog, the beach, and making friends!', 'Virgo', 'Yes', 26),
('Natasha', 'McMillan', 'natty@email.com', 'password', '1994-10-07', 'Toronto', 'Female', 'Florist and aspiring author. Looking for a friend to share ideas with!', 'Libra', 'Yes', 24),
('Matt', 'Powell', 'mattpow@email.com', 'password', '1993-12-27', 'Oakville', 'Male', 'Overall an easy going guy. Also a geek for Marvel and everything comics related.', 'Capricorn', 'Yes', 20),
('Trish', 'Sawyer', 'trish@email.com', 'password', '1994-02-11', 'Toronto', 'Female', 'Happiness never goes out of style!', 'Aquarius', 'Yes', 25),
('Sean', 'Porter', 'seanp@email.com', 'password', '1990-06-14', 'Toronto', 'Male', 'I’m awesome (don’t worry I think you are too).', 'Gemini', 'Yes', 28),
('Kim', 'Sanchez', 'kimmy@email.com', 'password', '1998-09-01', 'Toronto', 'Female', 'Either reading or travelling.', 'Virgo', 'Yes', 25),
('Kate', 'Sanchez', 'kate@email.com', 'password', '1999-10-07', 'Mississauga', 'Female', 'Lover of the outdoors, art, and travel.', 'Libra', 'Yes', 2),
('Mohamed', 'Ali', 'mo@email.com', 'password', '1999-04-19', 'Mississauga', 'Male', 'Always down to make new friends.', 'Aries', 'Yes', 1),
('TJ', 'Jung', 'tj@email.com', 'password', '1995-02-16', 'Toronto', 'Male', 'Just a guy who loves to code', 'Aquarius', 'Yes', 27),
('Mona','Waseem', 'mona@email.com', 'password', '1988-07-01', 'Toronto', 'Female', 'An animal activist and an in the works developer!', 'Cancer', 'Yes', 26),
('Beatrice', 'Kwan', 'beakwan@email.com', 'password', '1994-10-31', 'Toronto', 'Female', 'Looking for friends to go dancing with!', 'Scorpio', 'Yes', 29),
('Phil', 'Maye', 'phil@email.com', 'password', '1990-05-09', 'Toronto', 'Male', 'I do not want any friends', 'Taurus', 'Yes', 29),
('Kleir', 'Miranda', 'kleir@email.com', 'password', '1994-02-11', 'Mississauga', 'Female', 'Always looking for new food to try!', 'Aquarius', 'Yes', 0),
('Rose', 'Gopez', 'rosie@email.com', 'password', '1993-05-09', 'Toronto', 'Female', 'Who will be my next travel buddy?', 'Taurus', 'Yes', 31),
('Chris', 'Reyes', 'chrisr@email.com', 'password', '1991-12-27', 'Toronto', 'Male', 'My last picture will make you want to be friends with me.', 'Capricorn', 'Yes', 30),
('Jessica', 'de Bruyn', 'jess@email.com', 'password', '1982-08-24', 'Toronto', 'Female', 'I like Disney, theatre and various cheeses', 'Virgo', 'Yes', 30),
('Afsan', 'Khan', 'afsan@email.com', 'password', '1994-07-04', 'Mississauga', 'Male', 'Always happy to make friends.', 'Cancer', 'Yes', 20),
('David', 'Eaton', 'dave@email.com', 'password', '1989-07-03', 'Toronto', 'Male', 'Ready to make new friends!', 'Cancer', 'Yes', 29),
('Maureen', 'Ferguson', 'maureen@email.com', 'password', '1989-04-12', 'Toronto', 'Female', 'Fun loving musician.', 'Capricorn', 'Yes', 26),
('Chelsea', 'Oray', 'chels@email.com', 'password', '1993-09-11', 'Ajax', 'Female', 'Looking for a friend to cook with!', 'Virgo', 'Yes', 40),
('Mathias', 'Memmel', 'mathias@email.com', 'password', '1994-04-04', 'Toronto', 'Male', 'Law student, musician, and forever foodie! I spent most of the pandemic pretending that I run a Michelin-starred restaurant', 'Aries', 'Yes', 30),
('Grace', 'Keenleyside', 'grace@email.com', 'password', '1989-09-27', 'Toronto', 'Female', 'I like running, baking, singing, movies, theatre, singing, and laughing with my favourite people.', 'Libra', 'Yes', 28),
('Yaw', 'Attuah', 'yaw@email.com', 'password', '1982-05-20', 'Toronto', 'Male', 'I am super busy. A dad and a fun guy.', 'Taurus', 'Yes', 25),
('Andrew', 'Bray', 'andrewb@email.com', 'password', '1987-06-28', 'Toronto', 'Male', 'Do not let the High School Teacher title fool you. Once the bell rings, this guy is ready to PARTY.', 'Cancer', 'Yes', 32);



INSERT INTO photos (user_id, photo1_url, photo2_url, photo3_url, photo4_url)
VALUES 
(1, 'https://i.imgur.com/PkPhCXN.jpg', 'https://i.imgur.com/g7KhzFz.jpg', 'https://i.imgur.com/I28EmjM.jpg', 'https://i.imgur.com/ldA2mbz.jpg'),
(2, 'https://i.imgur.com/YO0LKUk.jpg', 'https://i.imgur.com/fBgW4Du.jpg', 'https://i.imgur.com/dC2o99f.jpg','https://i.imgur.com/ldHo18O.jpg'),
(3, 'https://i.imgur.com/zAkOsvd.jpg', 'https://i.imgur.com/vtL4mTg.jpg', 'https://i.imgur.com/AWjRkyr.jpg','https://i.imgur.com/s1es1cH.jpg'),
(4, 'https://i.imgur.com/BB7vcgK.jpg', 'https://i.imgur.com/UIgzJIH.jpg', 'https://i.imgur.com/zkzV4Yk.jpg','https://i.imgur.com/fKKEwdz.jpg'),
(5, 'https://i.imgur.com/msEdEpF.jpg', 'https://i.imgur.com/MVYCtJ6.jpg', 'https://i.imgur.com/oMTz2Ug.jpg','https://i.imgur.com/wvwQRr4.jpg'),
(6, 'https://images.unsplash.com/photo-1589566856690-fc68ac16845c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=668&q=80','https://images.unsplash.com/photo-1624759356182-4d147c997ef4?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=3101&q=80','https://images.unsplash.com/photo-1607735296380-b066a27182a3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=3064&q=80', 'https://images.unsplash.com/photo-1600361675085-7ad23d454309?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=760&q=80'),
(7, 'https://images.pexels.com/photos/8532778/pexels-photo-8532778.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', 'https://images.pexels.com/photos/8532756/pexels-photo-8532756.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', 'https://images.pexels.com/photos/8532623/pexels-photo-8532623.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/8532767/pexels-photo-8532767.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'),
(8, 'https://images.pexels.com/photos/4114828/pexels-photo-4114828.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', 'https://images.pexels.com/photos/4114741/pexels-photo-4114741.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/4115001/pexels-photo-4115001.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', 'https://images.pexels.com/photos/4113955/pexels-photo-4113955.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'),
(9, 'https://images.pexels.com/photos/4045541/pexels-photo-4045541.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', 'https://images.pexels.com/photos/4046158/pexels-photo-4046158.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', 'https://images.pexels.com/photos/4056529/pexels-photo-4056529.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', 'https://images.pexels.com/photos/4046314/pexels-photo-4046314.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'),
(10, 'https://images.pexels.com/photos/5749820/pexels-photo-5749820.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', 'https://images.pexels.com/photos/5749770/pexels-photo-5749770.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', 'https://images.pexels.com/photos/5749790/pexels-photo-5749790.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', 'https://images.pexels.com/photos/5749089/pexels-photo-5749089.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'),
(11, 'https://i.imgur.com/1R5U27H.jpg', 'https://i.imgur.com/K9P3ZwP.jpg', 'https://i.imgur.com/8qG1Fin.png', 'https://i.imgur.com/sWBQR41.jpg'),
(12, 'https://i.imgur.com/lfnqruz.jpg', 'https://i.imgur.com/XY8Rdez.jpg', 'https://i.imgur.com/Ck3Vea6.jpg', 'https://i.imgur.com/dCLzsXR.jpg'),
(13, 'https://i.imgur.com/KAh196M.jpg', 'https://i.imgur.com/KAh196M.jpg', 'https://i.imgur.com/KAh196M.jpg', 'https://i.imgur.com/KAh196M.jpg'),
(14, 'https://i.imgur.com/vRHygPK.jpg?1', 'https://i.imgur.com/vRHygPK.jpg?1', 'https://i.imgur.com/vRHygPK.jpg?1', 'https://i.imgur.com/vRHygPK.jpg?1'),
(15, 'https://i.imgur.com/dZoIHZ2.jpg', 'https://i.imgur.com/cgKTkjf.jpg', 'https://i.imgur.com/DPsxtQC.jpg', 'https://i.imgur.com/l69ux1y.png'),
(16, 'https://i.imgur.com/UEs6lC7.jpg?1', 'https://i.imgur.com/45Obbw6.jpg', 'https://i.imgur.com/TYrS0ap.jpg', 'https://i.imgur.com/dhhYSTw.jpg'), 
(17, 'https://i.imgur.com/XzwdBsh.jpg', 'https://i.imgur.com/45Obbw6.jpg', 'https://i.imgur.com/3OpA5QS.jpg', 'https://i.imgur.com/0YFD3OB.jpg'),
(18, 'https://i.imgur.com/GRr36Oj.jpg', 'https://i.imgur.com/KIHS4k9.jpg', 'https://i.imgur.com/zMCE3xe.jpg', 'https://i.imgur.com/3rLbTnI.jpg'),
(19, 'https://i.imgur.com/ax88gMu.jpg', 'https://i.imgur.com/v5o3R7a.jpg', 'https://i.imgur.com/ZpMCBE9.jpg', 'https://i.imgur.com/qfCUjxF.jpg'),
(20, 'https://i.imgur.com/AJdMtmk.jpg', 'https://i.imgur.com/wtcAy6b.jpg', 'https://i.imgur.com/c1mImcp.jpg', 'https://i.imgur.com/TSa89SG.jpg'),
(21, 'https://i.imgur.com/0RlQTkb.jpg', 'https://i.imgur.com/prmnsi8.jpg', 'https://i.imgur.com/eWzDoEl.jpg', 'https://i.imgur.com/TaQ3df8.jpg'),
(22, 'https://i.imgur.com/B4C9o64.jpg', 'https://i.imgur.com/hoG9hta.jpg', 'https://i.imgur.com/NnBGHdE.jpg', 'https://i.imgur.com/02PgN4H.jpg'),
(23, 'https://i.imgur.com/O1DJZ7X.jpg', 'https://i.imgur.com/w8PkqDo.jpg', 'https://i.imgur.com/zpYv7wj.jpg', 'https://i.imgur.com/mlzyUI6.jpg'),
(24, 'https://i.imgur.com/qH9vmb7.jpg', 'https://i.imgur.com/vNlKwvE.jpg', 'https://i.imgur.com/Wj5IS9S.jpg', 'https://i.imgur.com/pfDcbvm.jpg'),
(25, 'https://i.imgur.com/SJeRCkU.png', 'https://i.imgur.com/NgaI1aS.png', 'https://i.imgur.com/pnLSZJx.png', 'https://i.imgur.com/nqRDi0W.png'),
(26, 'https://i.imgur.com/clKwNAf.jpg', 'https://i.imgur.com/jor3HS2.jpg', 'https://i.imgur.com/Ph83Fx5.jpg', 'https://i.imgur.com/WIOUUk4.jpg'),
(27, 'https://i.imgur.com/DUfA1Pv.jpg', 'https://i.imgur.com/6iFbrf8.jpg', 'https://i.imgur.com/OdCPsTc.jpg', 'https://i.imgur.com/90K56nq.jpg'),
(28, 'https://i.imgur.com/X3GVkts.jpg', 'https://i.imgur.com/Xu6Hj7Q.jpgv', 'https://i.imgur.com/dJmQ5sP.jpg', 'https://i.imgur.com/xuSfApR.jpg'),
(29, 'https://i.imgur.com/SehavKG.jpg', 'https://i.imgur.com/ESaKlG3.jpg', 'https://i.imgur.com/Ok3UdpP.png', 'https://i.imgur.com/XKoLMw9.jpg');


INSERT INTO interests (user_id, reading, tv_movies, fitness, hiking, arts_culture, music, gaming, travel, studying, sports, eating_out, going_out)
VALUES 
(1, true, true, false, false, true, true, true, false, true, false, false, true),
(2, false, false, false, false, true, true, false, false, false, true, false, true),
(3, true, false, true, false, true, false, false, false, true, true, false, true),
(4, false, true, false, false, true, true, false, false, true, false, true, true),
(5, true, false, false, true, true, false, true, false, false, true, true, false),
(6, true, false, true, true, true, true, true, false, true, false, true, false),
(7, true, true, false, false, true, false, false, false, true, false, false, false),
(8, true, true, false, false, false, true, true, false, false, true, false, false),
(9, false, false, true, true, true, false, false, true, false, false, true, true),
(10, true, false, true, true, true, false, false, true, true, true, true, false),
(11, true, false, false, true, true, true, true, true, true, false, true, false),
(12, false, false, false, true, true, false, false, true, false, false, false, true),
(13, true, false, true, true, false, true, false, true, false, true, false, true),
(14, true, true, false, false, false, false, true, false, true, false, false, false),
(15, false, true, false, true, true, true, false, false, false, false, true, true),
(16, true, true, true, true, true, false, false, true, false, false, true, true),
(17, false, true, true, false, true, true, true, false, false, true, false, true),
(18, true, true, false, false, true, true, true, true, false, false, true, false),
(19, true, true, false, false, true, false, false, true, false, false, true, true),
(20, false, false, false, false, true, true, false, true, false, false, true, true),
(21, true, true, false, true, true, true, false, true, true, false, true, true),
(22, true, true, false, false, true, true, true, true, true, true, true, false),
(23, true, true, false, false, true, true, false, true, false, false, true, false),
(24, false, false, true, true, true, true, false, false, false, false, true, true),
(25, true, true, false, true, true, true, false, true, false, false, true, false),
(26, true, false, false, false, true, true, true, false, true, false, false, true),
(27, false, true, true, true, true, true, false, true, false, false, true, false),
(28, false, true, true, false, false, true, false, true, false, true, false, false),
(29, true, true, true, true, true, true, false, false, false, true, true, true);

INSERT INTO potential_matches (user1_id, user2_id, best_friend)
VALUES 
(1, 2, false),
(1, 3, false),
(1, 4, false),
(1, 5, false),
(4, 5, true),
(2, 4, false),
(19, 18, true),
(16, 18, false),
(12, 18, false),
(10, 18, false),
(24, 18, false),
(6, 18, true),
(14, 18, false),
(2, 18, false),
(22, 18, false),
(27, 18, false),
(29, 18, false);

INSERT INTO matches (user1_id, user2_id, best_friend)
VALUES 
(1, 2, false),
(1, 3, false),
(1, 4, false),
(18, 19, true),
(18, 17, false),
(18, 2, false),
(18, 1, false),
(16, 17, true),
(16, 3, false),
(16, 5, false),
(16, 8, false);

INSERT INTO messages (match_id, sender_id, receiver_id, message, sent_at)
VALUES
(1, 2, 1, 'I think my other friend and I are watching the Raps tonight. Want to come with us?', '2021-08-19 10:23:54'),
(2, 3, 1, 'I might visit Toronto next week. We can go for a hike!', '2021-08-19 08:30:01'),
(3, 4, 1, 'Let me know when you want to link up and take some pictures xx', '2021-08-22 23:23:54'),
(3, 1, 4, 'Sure. Down whenever.', '2021-08-24 23:23:54'),
(4, 18, 19, 'Omg you went to the Van Gogh exhibit?!', '2021-08-22 23:24:54'),
(4, 19, 18, 'Yeah it was so pretty', '2021-08-22 23:26:54');
